// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRrC7vElUTt3GOYvhsLe85jCvDKlzfB6U',
    appId: '1:694964356586:web:b1147a1e6d1ebc9ae31e93',
    messagingSenderId: '694964356586',
    projectId: 'parchelapp-76af7',
    authDomain: 'parchelapp-76af7.firebaseapp.com',
    storageBucket: 'parchelapp-76af7.appspot.com',
    measurementId: 'G-XVJJJJ384C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKmPr6s509-jR-1DUBLCPcz_FUmnjkeUY',
    appId: '1:694964356586:android:d96903db49948d38e31e93',
    messagingSenderId: '694964356586',
    projectId: 'parchelapp-76af7',
    storageBucket: 'parchelapp-76af7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXdcYpk0_MJx8taK7TaWVCJLz5iM7AgYw',
    appId: '1:694964356586:ios:84e803b6b42691fae31e93',
    messagingSenderId: '694964356586',
    projectId: 'parchelapp-76af7',
    storageBucket: 'parchelapp-76af7.appspot.com',
    iosClientId: '694964356586-cetc743f5mh3jpq9it9dmkqoncbrepp2.apps.googleusercontent.com',
    iosBundleId: 'co.com.parchelapp',
  );
}
